In [1]:
import pandas as pd

In [3]:
pairs = pd.read_csv('data/pairs_final.csv', index_col=0)
display(pairs.head())

cpds = pd.read_csv('data/compounds_final.csv', index_col=0)
display(cpds.head())

,Reactant_pair,KEGG_reactions,source,target,CAR,RPAIR_main
0,C00003_C00006,"R00104,R00118",C00003,C00006,-999.0,True
1,C00003_C00153,"R00102,R00555,R03447,R04074,R10629,R10633,R106...",C00003,C00153,-999.0,True
2,C00003_C00301,R00102,C00003,C00301,-999.0,True
3,C00003_C00455,"R00103,R00137",C00003,C00455,-999.0,True
4,C00003_C00857,"R00189,R00257",C00003,C00857,-999.0,True

,id,formula,mol_weight,Fe,S,W,P,Se,R,Mo,...,H,Ni,O,F,Hg,As,I,X,N,polymer
0,C00001,H2O,18.016,0,0,0,0,0,0,0,...,2,0,1,0,0,0,0,0,0,0
1,C00002,C10H16N5O13P3,507.188,0,0,0,3,0,0,0,...,16,0,13,0,0,0,0,0,5,0
2,C00003,C21H28N7O14P2,664.444,0,0,0,2,0,0,0,...,28,0,14,0,0,0,0,0,7,0
3,C00004,C21H29N7O14P2,665.452,0,0,0,2,0,0,0,...,29,0,14,0,0,0,0,0,7,0
4,C00005,C21H30N7O17P3,745.430,0,0,0,3,0,0,0,...,30,0,17,0,0,0,0,0,7,0